config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :my_threads do
    resources :comments, controller: "my_threads/comments"
  end
  root :to => "my_threads#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :my_thread
    validates :comment, presence: true
end

app/models/my_thread.rb
class MyThread < ApplicationRecord
  has_many :comment, :dependent => :destroy
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end
 

app/controllers/my_threads/comments_controller.rb
class MyThreads::CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  
  # GET my_thread/:my_thread_id/comments/
  def index
    @my_thread = MyThread.find(params[:my_thread_id])
    @comments = Comment.where(my_thread_id: @my_thread)
  end

  # GET /my_threads/:my_thread_id/comments/new
  def new
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = Comment.new
  end
  
  #POST /my_threads/:my_thread_id/comments
  def create
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = Comment.new(comment_param)

    respond_to do |format|
      if @comment.save
        format.html{ redirect_to my_thread_comments_path(@my_thread), notice: "Comment was successfully created."}
      else
        format.html{ render :new }
      end
    end
  end

  #GET /my_threads/:my_thread_id/comments/:id/edit
  def edit
    @my_thread = MyThread.find(params[:my_thread_id])
  end

  #PATCH/PUT /my_threads/:my_thread_id/comments/:id
  def update
    @my_thread = MyThread.find(params[:my_thread_id])
    respond_to do |format|
      if @comment.update(comment_param)
        format.html { redirect_to my_thread_comments_path(@my_thread), notice: "Comment was successfully updated."}
      else
        format.html { render :edit }
      end
    end
  end

  #DELETE /my_threads/:my_thread_id/comments/:id
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to my_thread_comments_path(params[:my_thread_id], notice: "Comment was successfully destroyed")}
    end
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_param
    params.require(:comment).permit(:comment).merge(my_thread_id: params[:my_thread_id])
  end
end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
    before_action :set_my_thread, only: [:show,:edit,:update,:destroy]

    def new
        @my_thread = MyThread.new
    end

    def index
        @my_threads = MyThread.all
    end

    #GET /my_threads/1
    def show
        redirect_to my_thread_comments_path(@my_thread)
    end

    #GET /my_threads/1/edit
    def edit
        @my_thread = MyThread.find(params[:id])
    end

    #POST /my_threads
    def create
        @my_thread = MyThread.new(my_thread_params)

        respond_to do |format|
            if @my_thread.save
                format.html { redirect_to my_threads_path, notice: "My Threads was successfully created."}
            else
                format.html {render :new}
            end
        end
    end
    
    #PATCH/PUT /my_thread/1
    def update
        #htmlのformatをrespond_toで生成して.updateが通れば#index,elseなら#editへ遷移
        respond_to do |format|
            if @my_thread.update(my_thread_params)
                format.html {redirect_to my_threads_path(@my_thread), notice: "My thread was successfully updated."}
            else
                format.html {render :edit} #renderはAction内からViewを呼び出すmethod edit.html.erbを呼ぶ
            end
        end
    end

    #DELETE /my_threads/1
    def destroy
        @my_thread.destroy
        respond_to do |format|
            format.html { redirect_to my_threads_url, notice: "My thread was successfully destroyed."}
        end
    end

    private
    def set_my_thread
        @my_thread = MyThread.find(params[:id])
    end

    #Never trust parameters from internet
    def my_thread_params
        params.require(:my_thread).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_threads/comments_helper.rb
module MyThreads::CommentsHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardPlus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <p>
    <%# DELETE /users/sign_out %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>

    
  </body>
</html>

app/views/my_threads/_form.html.erb
<%= form_with(model: my_thread, local: true) do |form| %>
  <% if my_thread.errors.any? %>
  <div id = "error_explanation">
    <h2><%= pluralize(my_thread.errors.count, "error" ) %> prohibited this my_thread from being saved:</h2>
    <ul>
    <%= my_thread.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<div class = "field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div>
  <%= form.submit %>
</div>

<% end %>

app/views/my_threads/comments/_form.html.erb
<%= form_with(model: [my_thread,comment], local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id = "error_explanation">
      <h2><%= pluralize(comment.errors.count, "error")%> prohibited this comment from being saved:</h2>
      
      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
     <%= form.label :comment %>
     <p>
     <%= form.text_field :comment %>
  </div>

  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

app/views/my_threads/comments/edit.html.erb
<h1>Editing comment</h1>
<%= render "form", my_thread: @my_thread, comment: @comment %>
<%= link_to "Back", my_thread_comments_path(@my_thread) %>

app/views/my_threads/comments/index.html.erb
<p id = "notice"><%= notice %></p>
<h1>Comments</h1>

<table>
    <thead>
        <tr>
            <th>My Thread</th>
            <th>Comment</th>
            <th colspan = "3"></th>
        </tr>
    </thead>
    <tbody>
        <% @comments.each do |comment| %>
        <tr>
            <td><%= comment.comment %></td>
            <td><%= link_to "Edit", edit_my_thread_comment_path(@my_thread,comment) %></td>
            <td><%= link_to "Destroy", my_thread_comment_path(@my_thread,comment), method: :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<br/>

<%= link_to "New Comment", new_my_thread_comment_path(@my_thread) %>
<%= link_to "Back", my_threads_path %>

app/views/my_threads/comments/new.html.erb
<h1>New comment</h1>
<%= render "form", comment: @comment, my_thread: @my_thread %>
<%= link_to "Back", my_thread_comments_path(@my_thread) %>

app/views/my_threads/edit.html.erb
<h1>Edit Thread</h1>
<%= render partial:"form", :locals => {my_thread: @my_thread}%>
<%= link_to "back", my_threads_path %>

app/views/my_threads/index.html.erb
<p id = "notice"><%= notice %></p>
<h1>My Threads</h1>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @my_threads.each do |my_thread| %>
        <tr>
            <td><%= my_thread.title %></td>
            <td><%= link_to 'show', my_thread_path(my_thread)%></td>
            <td><%= link_to 'edit', edit_my_thread_path(my_thread)%></td>
            <td><%= link_to 'destroy', my_thread_path(my_thread), method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to "new my thread", new_my_thread_path %>

app/views/my_threads/new.html.erb
<h1>New Thread</h1>
<%= render partial: "form", locals: {my_thread: @my_thread} %>
<%= link_to "back", my_threads_path %>